name: Commax controller
description: Commax wallpad control with EW11
version: 0.0.29
slug: wallpad
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
map:
  - share:rw
boot: auto
startup: application
options:
  ew11:
    ip: 192.168.x.x
    port: 8899
    sendDelay: 100
  mqtt:
    ip: 192.168.x.x
    username: id
    password: pw
    receiveDelay: 10000
schema:
  ew11:
    ip: str
    port: int
    sendDelay: int
  mqtt:
    ip: str
    username: str
    password: str
    receiveDelay: int
